# Generated by Django 3.1.4 on 2020-12-12 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_remove_task_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='task3',
        ),
        migrations.AddField(
            model_name='task',
            name='Задание 3',
            field=models.CharField(blank=True, default='-', max_length=100),
        ),
        migrations.AlterField(
            model_name='task',
            name='task1',
            field=models.CharField(blank=True, default='-', max_length=100),
        ),
        migrations.AlterField(
            model_name='task',
            name='task2',
            field=models.CharField(blank=True, default='-', max_length=100),
        ),
        migrations.AlterField(
            model_name='task',
            name='task4',
            field=models.CharField(blank=True, default='-', max_length=100),
        ),
        migrations.AlterField(
            model_name='task',
            name='task5',
            field=models.CharField(blank=True, default='-', max_length=100),
        ),
    ]
