# Generated by Django 3.1.4 on 2020-12-12 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_auto_20201212_1048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='Предмет',
            new_name='subject',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='Задание 1',
            new_name='task1',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='Задание 2',
            new_name='task2',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='Задание 3',
            new_name='task3',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='Задание 4',
            new_name='task4',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='Задание 5',
            new_name='task5',
        ),
    ]
